name: Build and Security Scan

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: rmeta

jobs:
  build-image:
    runs-on: arc-runner-set-2

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 1
      - name: Install curl 
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libc6 -y
          sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev jq curl -y
         
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: "${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }} "
          tags: type=sha,format=long

      - name: Build and Push container images
        uses: docker/build-push-action@v6.4
        id: build-and-push
        with:
          platforms: linux/amd64
          #,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ github.run_id }}
          #${{ steps.docker_meta.outputs.tags }}

      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
